import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import {nanoid} from 'nanoid'

import Footer from './comps/footer'
// import InputSection from './comps/inputSection'
import MainDisplay from './comps/mainDisplay'
import AboveFooter from './comps/aboveFooter'
import WholeBrandBlocks from './comps/wholeBrandBlocks'
import AdvancedAnalytics from './comps/advancedAnalytics'
import NavBar from './comps/navComps/navBar'

export default function Home() {


  const [inputLink, setinputLink] = useState('')
  
  const [currentShortLink, setcurrentShortLink] = useState('Short link will appear here')

  const [linkArr, setlinkArr] = useState([])

  function updateInputLink(event){
    setinputLink(event.target.value)
  }

  console.log(inputLink);
  
  

  async function shortFunction(){
    var url = new URL(" https://api.shrtco.de/v2/shorten?url=example.org/very/long/link.html");
    url.searchParams.set('url', inputLink);
    fetch(url)
    .then(response => response.json())
    .then( (data)=> {
      const Data=(data.result.full_short_link)
      console.log(Data);
      setcurrentShortLink(Data);

      const NewArr={
        id:nanoid(),
        longText: inputLink,
        shorttext: (data.result.full_short_link)
      }
      const FinalArr=[...linkArr,NewArr]
      setlinkArr(FinalArr)
      console.log(linkArr)
      setinputLink('')

    })}

    function copyFunction(){
      navigator.clipboard.writeText(currentShortLink);
      alert("Link Copied: " + currentShortLink);
    }

  return (
    <div>
    <div className={styles.container}>
      <Head>
        <title>Url-Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>

      <NavBar/>

      <MainDisplay/>


{/* This is the input Section that I am not converting into a component becausethe states are defined and index.json
and if we import export it, error occurs */}

      <div className={styles.inputSection}>
      <div className={styles.inputDiv}>

          <div className={styles.inputfield}>
            <input className={styles.inputField}
                  onChange={updateInputLink}
                 
                  type='text'
                  value={inputLink}
                  id='inputLink'
                    placeholder='Shorten a link here'
            ></input>
          </div>
            
          <button className={styles.shortenButton} 
                  onClick={shortFunction}
                  
          >Shorten it!</button>

      </div>
      </div>

  {/* Input section ends here */}
      

     
      <div className={styles.vShortenDiv} >
            <div className={styles.shortLinkMainDiv}>
                <div className={styles.shortLinkText}><h1>{currentShortLink}</h1></div>
            </div>
                <div >
                  <button  className={styles.vShortenButton} onClick={copyFunction}>Copy Link</button>
                </div>
      </div>

     <AdvancedAnalytics/>

    </div>

    <WholeBrandBlocks/>

     <AboveFooter/>

     <Footer/>

    </div>
  )
}
