import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import BrandBlocks from './comps/brandBlocks'
import {nanoid} from 'nanoid'
import Footer from './comps/footer'
import InputSection from './comps/inputSection'
import MainDisplay from './comps/mainDisplay'
import AboveFooter from './comps/aboveFooter'
import WholeBrandBlocks from './comps/wholeBrandBlocks'

export default function Home() {


  const [inputLink, setinputLink] = useState('');;
  
  const [currentShortLink, setcurrentShortLink] = useState('Short link will appear here')

  const [linkArr, setlinkArr] = useState([]);
  
  const [isOpen, setisOpen] = useState(false)

  const [shortenedLink, setshortenedLink] = useState()

  function updateInputLink(event){
    setinputLink(event.target.value)

  }
  console.log(inputLink);
  
  

  async function shortFunction(){
    var url = new URL(" https://api.shrtco.de/v2/shorten?url=example.org/very/long/link.html");
    url.searchParams.set('url', inputLink);
    fetch(url)
    .then(response => response.json())
    .then( (data)=> {
      const Data=(data.result.full_short_link)
      console.log(Data);
      setcurrentShortLink(Data);

      const NewArr={
        id:nanoid(),
        longText: inputLink,
        shorttext: (data.result.full_short_link)
      }
      const FinalArr=[...linkArr,NewArr]
      setlinkArr(FinalArr)
      console.log(linkArr)
      setinputLink('')

    })}

    function copyFunction(){
      navigator.clipboard.writeText(currentShortLink);
      alert("Link Copied: " + currentShortLink);
    }

  return (
    <div>
    <div className={styles.container}>
      <Head>
        <title>Url-Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>

      <div className={styles.navWrapper}>
      <nav >
        <div className={styles.containerNav}>
        <div><Image
            src="/logo.svg"
            width={170}
            height={50}
            alt='logo'
            layout='intrinsic'
        ></Image></div>
        <div className={styles.menu}>
          
            <a href=''>Features </a>
            <a href=''>Pricing </a>
            <a href=''>Resources</a>
        </div>
        <div>
            <button  className={styles.hamburger}>
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>
        </div>
      </nav>
      </div>

      <MainDisplay/>

      <InputSection/>


      

     
      <div className={styles.vShortenDiv} >
            <div className={styles.shortLinkMainDiv}>
                <div className={styles.shortLinkText}><h1>{currentShortLink}</h1></div>
            </div>
                <div >
                  <button  className={styles.vShortenButton} onClick={copyFunction}>Copy Link</button>
                </div>
      </div>

      <div className={styles.secondPart}>

          <div className={styles.secondRestrictor}>
              <div className={styles.secondMainText}>
                  Advanced Statistics
              <div className={styles.secondPara}>
              <p>Track how your links are perorming across the Web with our Advanced statistics Dashboard</p>
              </div>
              </div>
          </div>
      </div>

    </div>

    <WholeBrandBlocks/>

     <AboveFooter/>

     <Footer/>

    </div>
  )
}
